celerity/SimSYCL

- test/usm_tests.cc
- ASAN was complaining about memory leak. Harmless in tests, but it's nice to have a clean run with ASAN, right?
- Also check that when asking for aligned memory the returned memory is actually aligned.
> Fix ASAN complaint with usm_tests, check alignment

- include/simsycl/detail/allocation.hh
- src/simsycl/system.cc
- test/CMakeLists.txt
- test/alloc_tests.cc
Fixed a bug regarding aligned_alloc on POSIX-compliant systems (macOS).
Added a test for this case.
> Fixed bug with aligned alloc for macos

- .github/workflows/simsycl_ci.yml
This update addresses the issues with the macOS CI by bumping the Boost version to 1.81.0 and adding the necessary architecture flag.
> [CI] Add arch to install_boost to fix macos CI

- include/simsycl/sycl/kernel.hh
- src/simsycl/kernel.cc
This patch resolves an issue in Clang version 17 and above on macOS, where the standard library contains a bug that prevents std::type_info instances of the same type from comparing as equal when used across shared libraries.
> Fixes a bug with (real) Clang on MacOS

- include/simsycl/detail/check.hh
- include/simsycl/detail/lock.hh
- include/simsycl/detail/reference_type.hh
- include/simsycl/schedule.hh
- include/simsycl/sycl/accessor.hh
- include/simsycl/sycl/buffer.hh
- include/simsycl/sycl/device.hh
- include/simsycl/sycl/device_selector.hh
- include/simsycl/sycl/event.hh
- include/simsycl/sycl/exception.hh
- include/simsycl/sycl/forward.hh
- include/simsycl/sycl/platform.hh
- include/simsycl/sycl/queue.hh
- include/simsycl/system.hh
- src/simsycl/check.cc
- src/simsycl/device.cc
- src/simsycl/kernel.cc
- src/simsycl/platform.cc
- src/simsycl/schedule.cc
- src/simsycl/system.cc
- test/math_tests.cc
Overall, SimSYCL has very little shared mutable state:
Fiber scheduling always happens inside a `parallel_for`, so it will never cross thread boundaries. The corresponding `cooperative_schedule` and "return fiber" can be made thread-local.
For where there is globally visible shared state (system config, USM allocations, buffer access validation), I've introduced a global lock (named `system_lock`, which is backed by a singleton mutex). All shared mutable state is now explicitly wrapped in a `mutable shared_state<>`, which only grants access to its interior when a `system_lock` is in scope.
To guarantee command-group ordering across threads without tracking dependencies explicitly, `submit` (and all similar functions) hold the `system_lock` while they're running.
With this patch, Celerity …
> Make SimSYCL thread-safe

- include/simsycl/sycl/accessor.hh
Fixup for #14 . The `<1>` specialization is needed for the `accessor<0>` implementation, not the generic one.
> Fix `command_group_access_guard` type usage

- include/simsycl/sycl/vec.hh
Found via CTS: `vec::load` / `store` now have overloads for raw pointers.
> Implement vec::load from / store to raw pointer

- include/simsycl/sycl/marray.hh
Found via CTS. This code was half-heartedly copy pasted from `vec.hh` before.
> Fix detail trait type: `sycl::marray` is templated on `size_t`, not `int`

- include/simsycl/sycl/handler.hh
`fill` is just a kernel, it was implemented with the internal `sequential_for` helper instead of `handler::parallel_for` - not sure exactly what didn't work, but afaic this is the more straightforward implementation anyway.
> Fix implementation of `handler::fill`

- include/simsycl/sycl/queue.hh
- src/simsycl/queue.cc
`queue::queue<Selector>` was implemented in the .cc file instead of the header, causing linker errors.
I've used the opportunity to check the property that devices must be in the provided context, if any.
> Implement templated queue ctor overloads

- include/simsycl/sycl/buffer.hh
This was missing its (trivial) implementation.
> Implement `property::buffer::context_bound::get_context()`

- include/simsycl/sycl/accessor.hh
- include/simsycl/sycl/buffer.hh
- include/simsycl/sycl/forward.hh
- include/simsycl/sycl/handler.hh
- include/simsycl/sycl/reduction.hh
- test/reduction_tests.cc
The function was not callable so far, it simply referenced an unimplemented function on `accessor` of the same name.
Calling `buffer_state::write_back` requires the state to be available inside `accessor`, which is why I refactored `buffer` to internally expose its `state` rather than pointers and ranges individually. This in turn needs type erasure on Allocator, which I quickly added as well.
> Properly implement `handler::update_host`

- include/simsycl/sycl/multi_ptr.hh
- src/simsycl/queue.cc
- `multi_ptr &operator=` should return `*this`
- `context::get_devices` returns a temporary, so we should not mix iterators from multiple calls to it.
> Fix a few issues found by CppCheck

- src/simsycl/schedule.cc
> Fix: Add global offset to global id in ND-range parallel for

- include/simsycl/sycl/accessor.hh
Accessor implementations confused `shared_ptr::operator bool` with `shared_ptr<bool>::operator*`.
Found by CTS `accessor_placeholder` tests.
> Fix `is_placeholder()` condition for generic accessors

- include/simsycl/sycl/property.hh
- src/simsycl/check.cc
Spec requires us to throw `errc::invalid`, instead of triggering a SimSYCL check as we do currently.
Found by CTS `queue` test.
> Throw `sycl::exception` on invalid call to `get_property()`

- .github/workflows/simsycl_ci.yml
- CMakeLists.txt
- cmake/simsycl-config.cmake.in
This fixes the [CMP0167](https://cmake.org/cmake/help/latest/policy/CMP0167.html) warning for SimSYCL and all consuming projects with any recent CMake version.
Since we already require Boost 1.70, we need no fallback or additional handling.
To make it work in CI, I also had to enable CMP0144 (which should eventually become the default behaviour as far as I understand it). I didn't run into this issue locally.
> Fix CMP0167 CMake warning

- README.md
- ci/confirm_cts_state.py
- ci/cts_state.csv
- ci/render_cts_state.py
- resources/cts_state.svg
Adds the "CTS State" Google Sheet I had lying around to the repo, and introduces a script to automatically build / run CTS tests to verify it's still up to date. This should make finding regressions and missed spec updates locally easier.
Eventually we want to integrate this into CI, but this requires KhronosGroup/SYCL-CTS/pull/871 to be merged first (+some CI integration work on our side).
> Tooling: Track and verify CTS state

- include/simsycl/sycl/atomic_ref.hh
I ran into this while developing some code with SimSYCL and then executing it on other platforms.
SimSYCL (helpfully, and, in my opinion, unproblematically) allows `atomic_ref<bool>`, but the spec does not.
It's easier to fix SimSYCL for now than the spec.
While implementing this we also found that it's currently very strange for the spec to list a limited set of types -- specifically not including any pointers -- but *also* a specialization for pointers. Some clarification seems needed there.
> Restrict atomic_ref types in accordance with the spec

- include/simsycl/sycl/vec.hh
This is part of a series of four consecutive pull requests implementing some of the SYCL clarifications for `sycl::vec`.
This pull request implements the behavior specified in https://github.com/KhronosGroup/SYCL-Docs/pull/668#issue-2715744864, which fixes `sycl::vec` constructors.
> Fix vec constructors

- include/simsycl/sycl/vec.hh
This is the second part of a series of four pull requests addressing some SYCL clarifications for sycl::vec.
This pull request implements the behavior specified in https://github.com/KhronosGroup/SYCL-Docs/pull/669#issue-2715756663, which adds explicit vec conversions.
> Add explicit vec conversion

- include/simsycl/sycl/vec.hh
- test/vec_tests.cc
This is the fourth and last part of a series of four pull requests addressing some SYCL clarifications for `sycl::vec`.
This pull request implements the behavior specified in https://github.com/KhronosGroup/SYCL-Docs/pull/672#issue-2715771214, which changes the return type of 1-element named swizzles to `DataT &`.
> Change the return type of named swizzles
